config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	  get "followings" => "relationships#followings", as: "followings"
  	  get "followers" => "relationships#followers", as: "followers"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]

    if @range == 'User'
      @users = User.looks(params[:search], params[:word])
    elsif @range == 'Book'
      @books = Book.looks(params[:search], params[:word])
    elsif @range == 'tag'
      @books = Book.looks(params[:search], params[:word])
      @tags = Tag.looks(params[:search], params[:word])
    end
    render 'search_result'
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :word %>
    <%= f.select :range, options_for_select([['User'], ['Book']]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索" %>
  <% end %>
<% end %>

app/views/searches/_tag_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :word %>
    <%= f.hidden_field :range, :value => "tag"  %>
    <%= f.hidden_field :search, :value => "perfect" %>
    <%= f.submit 'タグ検索' %>
  <% end %>
<% end %>

app/views/searches/search_result.html.erb
<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
  <h2>Users search for "<%= @word %>"</h2>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      <% end %>
    </tbody>

  <% elsif @range == "Book" %>
    <!--検索対象モデルがBookの時 -->
    <h2>Books search for "<%= @word %>"</h2>
    <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image, size: '50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>

<% elsif @range == "tag" %>
  <h2>Books search for "<%= @word %>"</h2>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <!--タグリスト-->
        <td>
          <% book.tags.each do |tag| %>
            <li style="list-style: none;"><%= link_to tag.name, search_path(content: tag.name, range:"tag", value: "perfect") %></li>
          <% end %>
        </td>

      <td id="favorite_btn_<%= book.id %>">
          <%= render "favorites/favorite-btn", book: book %>
      </td>

    <p>
      <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
    </p>

      <td>
        <%= render "books/static.rate", book: book %>
      </td>

      </tr>
    <% end %>
  </tbody>
<% end %>
</table>